server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      acks: all
      retries: 2147483647
      delivery-timeout-ms: 120000
      linger-ms: 5
      request-timeout-ms: 30000
      enable-idempotence: true
      max-in-flight-requests-per-connection: 5
    consumer:
      group-id: resignation-service
      auto-offset-reset: earliest
app:
  kafka:
    topics:
      accounting: accounting.requests.v1
      security: security.requests.v1
      resignation: resignation.responses.v1
      notification: notification.requests.v1
    groups:
      accounting: accounting-service
      security: security-service
      resignation: resignation-service
      notification: notification-service
    retry:
      interval-ms: 1000
      max-retries: 3
    topic-config:
      defaults:
        partitions: 3
        replicas: 3
        min-in-sync-replicas: 2
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${JAEGER_URL:http://localhost:4318/v1/traces}