server:
  port: 0
app:
  timezone: Europe/Minsk
  accounting:
    base-url: ${ACCOUNTING_SERVICE_URL}
    endpoint: /api/v1/accounting/allocation
  profiler:
    base-url: ${PROFILER_SERVICE_URL}
    endpoint: /api/v1/cvs
  security:
    base-url: ${SECURITY_SERVICE_URL}
    endpoint: /api/v1/security/check
spring:
  application:
    name: resignation-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db.changelog/changelog.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true