spring:
  application:
    name: resignation-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db.changelog/changelog.xml

app:
  timezone: Europe/Minsk
  accounting:
    endpoint: /api/v1/accounting/allocation
  profiler:
    endpoint: /api/v1/cvs
  security:
    endpoint: /api/v1/security/check

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 5
        event-consumer-buffer-size: 20
        ignore-exceptions:
          - by.javaguru.jdmik7.resignation.api.exception.ResourceNotFoundException
          - by.javaguru.jdmik7.resignation.api.exception.ExternalServiceException
    instances:
      accounting-service:
        base-config: default
      security-service:
        base-config: default
      profiler-service:
        base-config: default

  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 5s
        ignore-exceptions:
          - by.javaguru.jdmik7.resignation.api.exception.ResourceNotFoundException
          - by.javaguru.jdmik7.resignation.api.exception.ExternalServiceException
    instances:
      accounting-service:
        base-config: default
      security-service:
        base-config: default
      profiler-service:
        base-config: default

outbox:
  scheduler:
    fixed-delay-ms: 5000
    batch-size: 10
    lock-timeout-minutes: 5
    worker-ids:
      - worker-1
      - worker-2
      - worker-3
